apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-rabbitmq
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://rabbitmq:5672"
  - name: username
    value: guest
  - name: password
    value: guest
  - name: durable
    value: true
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: true
  - name: deliveryMode
    value: 2
  - name: requeueInFailure
    value: true
  - name: prefetchCount
    value: 1
  - name: publisherConfirm
    value: true
  - name: enableDeadLetter
    value: true
  